     
{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .targetNamespace }}
    server: https://kubernetes.default.svc
  project: {{ .project }}
  source:
    path: chart
    repoURL: "ssh://git@github.com:22/{{ .github.organization }}/{{ .github.repository }}.git"
    targetRevision: {{ default "HEAD" .github.targetRevision }}
    helm:
      {{- if .helm }}
      passCredentials: {{ .helm.passCredentials }}
      valueFiles:
        {{- range .helm.valueFiles }}
        - {{ . }}
        {{- end }}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
