apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-artifact-registry-credentials-the-farmer
  namespace: birthdaypies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: google-artifact-registry-credentials-the-farmer
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: the-farmer_google-artifact-registry_dockerconfigjson